import sys
from PyQt5 import QtWidgets, QtGui, QtCore

class Window(QtWidgets.QWidget):
	def __init__(self):
		super().__init__()
		self.start()
	def start(self):
		self.screen = QtWidgets.QDesktopWidget().availableGeometry()
		self.setWindowTitle("Sample5")
		self.setGeometry((self.screen.width()/2)-150, (self.screen.height()/2)-250, 300, 500)
		self.setFixedSize(self.size());
		self.color = QtGui.QColor(127,127,127)
		self.setStyleSheet("QWidget {background-color: %s}" %self.color.name())
		self.ui_setup()
		self.show()
	def ui_setup(self):
		self.l1 = QtWidgets.QLabel(self)
		self.l1.setPixmap(QtGui.QPixmap("logo.png"))

		self.l2 = QtWidgets.QLabel(self)
		self.l2.setText("RGB Colors")
		self.l2.setStyleSheet("QLabel {color: white}")

		self.l3 = QtWidgets.QLabel(self)
		self.l3.setText("R: 127")
		self.l3.setStyleSheet("QLabel {color: red}")

		self.s_r = QtWidgets.QSlider(QtCore.Qt.Horizontal)
		self.s_r.setMinimum(0)
		self.s_r.setMaximum(255)
		self.s_r.setValue(127)
		self.s_r.setTickInterval(10)
		self.s_r.setTickPosition(QtWidgets.QSlider.TicksBelow)
		self.s_r.valueChanged.connect(self.s_change)

		self.l4 = QtWidgets.QLabel(self)
		self.l4.setText("G: 127")
		self.l4.setStyleSheet("QLabel {color: green}")

		self.s_g = QtWidgets.QSlider(QtCore.Qt.Horizontal)
		self.s_g.setMinimum(0)
		self.s_g.setMaximum(255)
		self.s_g.setValue(127)
		self.s_g.setTickInterval(10)
		self.s_g.setTickPosition(QtWidgets.QSlider.TicksBelow)
		self.s_g.valueChanged.connect(self.s_change)

		self.l5 = QtWidgets.QLabel(self)
		self.l5.setText("B: 127")
		self.l5.setStyleSheet("QLabel {color: blue}")

		self.s_b = QtWidgets.QSlider(QtCore.Qt.Horizontal)
		self.s_b.setMinimum(0)
		self.s_b.setMaximum(255)
		self.s_b.setValue(127)
		self.s_b.setTickInterval(10)
		self.s_b.setTickPosition(QtWidgets.QSlider.TicksBelow)
		self.s_b.valueChanged.connect(self.s_change)

		self.l6 = QtWidgets.QLabel(self)
		self.l6.setText("CheckBox")
		self.l6.setStyleSheet("QLabel {color: white}")

		self.chk1 = QtWidgets.QCheckBox(self)
		self.chk1.setText("CheckBox 1")
		self.chk2 = QtWidgets.QCheckBox(self)
		self.chk2.setText("CheckBox 2")

		self.l7 = QtWidgets.QLabel(self)
		self.l7.setText("RadioButton")
		self.l7.setStyleSheet("QLabel {color: white}")

		self.r1 = QtWidgets.QRadioButton(self)
		self.r1.setText("A")
		self.r1.setChecked(True)
		self.r2 = QtWidgets.QRadioButton(self)
		self.r2.setText("B")
		self.r3 = QtWidgets.QRadioButton(self)
		self.r3.setText("C")
		self.r4 = QtWidgets.QRadioButton(self)
		self.r4.setText("D")
		self.r5 = QtWidgets.QRadioButton(self)
		self.r5.setText("E")
		self.r6 = QtWidgets.QRadioButton(self)
		self.r6.setText("F")

		self.l8 = QtWidgets.QLabel(self)
		self.l8.setText("TextEdit")
		self.l8.setStyleSheet("QLabel {color: white}")

		self.te1 = QtWidgets.QTextEdit(self)
		self.te1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
		self.te1.setStyleSheet("QTextEdit {background-color: lightblue}")

		self.b1 = QtWidgets.QPushButton(self)
		self.b1.setText("Clear")
		self.b1.setStyleSheet("QPushButton {background-color: darkgreen; color: white}")
		self.b1.clicked.connect(self.btn_clicked)

		self.h1_box = QtWidgets.QHBoxLayout()
		self.h1_box.addStretch()
		self.h1_box.addWidget(self.l1)
		self.h1_box.addStretch()

		self.h2_box = QtWidgets.QHBoxLayout()
		self.h2_box.addStretch()
		self.h2_box.addWidget(self.chk1)
		self.h2_box.addStretch()
		self.h2_box.addWidget(self.chk2)
		self.h2_box.addStretch()

		self.h3_box = QtWidgets.QHBoxLayout()
		self.h3_box.addStretch()
		self.h3_box.addWidget(self.r1)
		self.h3_box.addStretch()
		self.h3_box.addWidget(self.r2)
		self.h3_box.addStretch()
		self.h3_box.addWidget(self.r3)
		self.h3_box.addStretch()
		self.h3_box.addWidget(self.r4)
		self.h3_box.addStretch()
		self.h3_box.addWidget(self.r5)
		self.h3_box.addStretch()
		self.h3_box.addWidget(self.r6)
		self.h3_box.addStretch()

		self.v_box = QtWidgets.QVBoxLayout()
		self.v_box.addLayout(self.h1_box)
		self.v_box.addWidget(self.l2)
		self.v_box.addWidget(self.l3)
		self.v_box.addWidget(self.s_r)
		self.v_box.addWidget(self.l4)
		self.v_box.addWidget(self.s_g)
		self.v_box.addWidget(self.l5)
		self.v_box.addWidget(self.s_b)
		self.v_box.addWidget(self.l6)
		self.v_box.addLayout(self.h2_box)
		self.v_box.addWidget(self.l7)
		self.v_box.addLayout(self.h3_box)
		self.v_box.addWidget(self.l8)
		self.v_box.addWidget(self.te1)
		self.v_box.addWidget(self.b1)
		self.setLayout(self.v_box)
	def s_change(self):
		r = self.s_r.value()
		g = self.s_g.value()
		b = self.s_b.value()

		self.l3.setText("R: "+ str(r))
		self.color.setRed(r)
		self.l4.setText("G: "+ str(g))
		self.color.setGreen(g)
		self.l5.setText("B: "+ str(b))
		self.color.setBlue(b)
		self.setStyleSheet("QWidget {background-color: %s}" %self.color.name())
	def btn_clicked(self):
		self.te1.setText("")

app = QtWidgets.QApplication(sys.argv)
w = Window()
sys.exit(app.exec_())